/*
 * Practice Zone exercises. No snake here, just Python!
 * Each exercise is checked by comparing what the code prints (`expect`)
 * and/or by running small Python `tests` after the player's code.
 */
(function (root) {
  'use strict';

  var GROUPS = [
    { id: 'print', name: 'Printing', world: 1, icon: 'sign' },
    { id: 'loops', name: 'for Loops', world: 2, icon: 'loop' },
    { id: 'vars', name: 'Variables & Maths', world: 3, icon: 'box' },
    { id: 'while', name: 'while Loops', world: 4, icon: 'clock' },
    { id: 'if', name: 'if / else', world: 5, icon: 'fork' },
    { id: 'def', name: 'Functions', world: 6, icon: 'book' },
    { id: 'lists', name: 'Lists', world: 7, icon: 'chest' },
    { id: 'boss', name: 'Challenges', world: 8, icon: 'diamond' }
  ];

  var EXERCISES = [
    // Printing
    { id: 'p1', group: 'print', title: 'Say Hello',
      task: 'Print the words <code>Hello, world!</code>',
      starter: 'print("Hello")\n',
      expect: 'Hello, world!',
      hint: 'Change the text inside the quotes to: Hello, world!',
      solution: 'print("Hello, world!")\n' },
    { id: 'p2', group: 'print', title: 'Three Lines',
      task: 'Print three lines: <code>I</code>, <code>love</code> and <code>Python</code>. Each word goes on its own line.',
      starter: 'print("I")\n',
      expect: 'I\nlove\nPython',
      hint: 'Use print() three times.',
      solution: 'print("I")\nprint("love")\nprint("Python")\n' },
    { id: 'p3', group: 'print', title: 'Maths Machine',
      task: 'Python can do maths! Print the answer to <code>7 * 6</code>. Don\u2019t use quotes, so Python works it out.',
      starter: 'print(2 + 2)\n',
      expect: '42',
      hint: 'print(7 * 6)  \u2190 * means times',
      solution: 'print(7 * 6)\n' },
    { id: 'p4', group: 'print', title: 'Snake Art',
      task: 'Draw this snake with print: <pre>~~~~@</pre> Then print <code>Hiss!</code> on the next line.',
      starter: 'print("~~~~@")\n',
      expect: '~~~~@\nHiss!',
      hint: 'Add another print for Hiss!',
      solution: 'print("~~~~@")\nprint("Hiss!")\n' },

    // for loops
    { id: 'l1', group: 'loops', title: 'Repeat 5 Times',
      task: 'Use a for loop to print <code>Python is fun!</code> five times.',
      starter: 'for i in range(2):\n    print("Python is fun!")\n',
      expect: 'Python is fun!\nPython is fun!\nPython is fun!\nPython is fun!\nPython is fun!',
      requires: ['for'],
      hint: 'Change range(2) into range(5).',
      solution: 'for i in range(5):\n    print("Python is fun!")\n' },
    { id: 'l2', group: 'loops', title: 'Count to 10',
      task: 'Print the numbers 1 to 10, each on its own line. Tip: <code>range(1, 11)</code> counts from 1 up to 10.',
      starter: 'for i in range(1, 4):\n    print(i)\n',
      expect: '1\n2\n3\n4\n5\n6\n7\n8\n9\n10',
      requires: ['for'],
      hint: 'range(1, 11) stops just BEFORE 11.',
      solution: 'for i in range(1, 11):\n    print(i)\n' },
    { id: 'l3', group: 'loops', title: 'Times Table',
      task: 'Print the 3 times table from <code>3</code> up to <code>30</code> (3, 6, 9 ... 30).',
      starter: 'for i in range(1, 11):\n    print(i)\n',
      expect: '3\n6\n9\n12\n15\n18\n21\n24\n27\n30',
      requires: ['for'],
      hint: 'print(i * 3)',
      solution: 'for i in range(1, 11):\n    print(i * 3)\n' },
    { id: 'l4', group: 'loops', title: 'Countdown',
      task: 'Print <code>3</code>, <code>2</code>, <code>1</code> and then <code>Blast off!</code>',
      starter: 'for i in range(3, 0, -1):\n    print(i)\n',
      expect: '3\n2\n1\nBlast off!',
      requires: ['for'],
      hint: 'The loop already counts down. Add print("Blast off!") after the loop, with no spaces in front.',
      solution: 'for i in range(3, 0, -1):\n    print(i)\nprint("Blast off!")\n' },

    // Variables
    { id: 'v1', group: 'vars', title: 'Your Name',
      task: 'Make a variable called <code>name</code> with the text <code>"Pip"</code>. Then print it.',
      starter: 'name = "Sam"\n',
      expect: 'Pip',
      tests: 'assert name == "Pip", "The variable name should be \\"Pip\\""',
      hint: 'name = "Pip"\nprint(name)',
      solution: 'name = "Pip"\nprint(name)\n' },
    { id: 'v2', group: 'vars', title: 'Apple Shop',
      task: 'Apples cost 3 coins each. Make <code>apples = 5</code> and <code>price = 3</code>. Print how much 5 apples cost.',
      starter: 'apples = 5\nprice = 3\n',
      expect: '15',
      tests: 'assert apples == 5 and price == 3, "Keep apples = 5 and price = 3"',
      hint: 'print(apples * price)',
      solution: 'apples = 5\nprice = 3\nprint(apples * price)\n' },
    { id: 'v3', group: 'vars', title: 'Level Up',
      task: 'Start with <code>score = 0</code>. Add 10 to the score three times, then print the score.',
      starter: 'score = 0\nscore = score + 10\n',
      expect: '30',
      hint: 'Write score = score + 10 three times (or use a loop!).',
      solution: 'score = 0\nfor i in range(3):\n    score = score + 10\nprint(score)\n' },
    { id: 'v4', group: 'vars', title: 'Join Text',
      task: 'You can join text with <code>+</code>. Make <code>animal = "snake"</code> and print <code>I am a snake</code> using the variable.',
      starter: 'animal = "snake"\nprint("I am a ")\n',
      expect: 'I am a snake',
      tests: 'assert animal == "snake", "Keep animal = \\"snake\\""',
      hint: 'print("I am a " + animal)',
      solution: 'animal = "snake"\nprint("I am a " + animal)\n' },
    { id: 'v5', group: 'vars', title: 'Add It Up',
      task: 'Use a loop and a variable to add up all the numbers from 1 to 10. Print the total.',
      starter: 'total = 0\nfor i in range(1, 11):\n    pass\nprint(total)\n',
      expect: '55',
      requires: ['for'],
      hint: 'Inside the loop: total = total + i',
      solution: 'total = 0\nfor i in range(1, 11):\n    total = total + i\nprint(total)\n' },

    // while loops
    { id: 'w1', group: 'while', title: 'While Counter',
      task: 'Use a while loop to print 1 to 5.',
      starter: 'n = 1\nwhile n <= 5:\n    print(n)\n',
      expect: '1\n2\n3\n4\n5',
      requires: ['while'],
      hint: 'Inside the loop, make n bigger: n = n + 1. Otherwise it never stops!',
      solution: 'n = 1\nwhile n <= 5:\n    print(n)\n    n = n + 1\n' },
    { id: 'w2', group: 'while', title: 'Doubling',
      task: 'Start with <code>x = 1</code>. While x is less than 100, print x and then double it (1, 2, 4 ... 64).',
      starter: 'x = 1\n',
      expect: '1\n2\n4\n8\n16\n32\n64',
      requires: ['while'],
      hint: 'while x < 100:\n    print(x)\n    x = x * 2',
      solution: 'x = 1\nwhile x < 100:\n    print(x)\n    x = x * 2\n' },
    { id: 'w3', group: 'while', title: 'Eat the Cake',
      task: 'There are 8 cake slices. While there are slices left, eat 3 (take away 3). Print how many slices are left at the end. It can\u2019t go below 0, so use <code>while slices >= 3</code>.',
      starter: 'slices = 8\n',
      expect: '2',
      requires: ['while'],
      hint: 'while slices >= 3:\n    slices = slices - 3\nprint(slices)',
      solution: 'slices = 8\nwhile slices >= 3:\n    slices = slices - 3\nprint(slices)\n' },

    // if / else
    { id: 'i1', group: 'if', title: 'Big or Small',
      task: 'The variable <code>number</code> is 42. If it is bigger than 10, print <code>big</code>, else print <code>small</code>.',
      starter: 'number = 42\nif number > 10:\n    print("big")\n',
      expect: 'big',
      tests: 'assert number == 42',
      requires: ['if', 'else'],
      hint: 'Add:\nelse:\n    print("small")',
      solution: 'number = 42\nif number > 10:\n    print("big")\nelse:\n    print("small")\n' },
    { id: 'i2', group: 'if', title: 'Password',
      task: 'Change <code>password</code> to <code>"sssnake"</code>. Then, if <code>password == "sssnake"</code> print <code>Welcome!</code>, else print <code>Go away!</code>',
      starter: 'password = "hello"\n',
      expect: 'Welcome!',
      requires: ['if', 'else'],
      hint: 'Use == to compare two things.',
      solution: 'password = "sssnake"\nif password == "sssnake":\n    print("Welcome!")\nelse:\n    print("Go away!")\n' },
    { id: 'i3', group: 'if', title: 'Even or Odd',
      task: 'For each number from 1 to 6, print <code>odd</code> or <code>even</code>. Tip: <code>n % 2 == 0</code> is True when n is even.',
      starter: 'for n in range(1, 7):\n    print(n)\n',
      expect: 'odd\neven\nodd\neven\nodd\neven',
      requires: ['for', 'if'],
      hint: 'if n % 2 == 0:\n    print("even")\nelse:\n    print("odd")',
      solution: 'for n in range(1, 7):\n    if n % 2 == 0:\n        print("even")\n    else:\n        print("odd")\n' },
    { id: 'i4', group: 'if', title: 'Fizz Buzz',
      task: 'Print the numbers 1 to 15. For multiples of 3 print <code>Fizz</code>, for multiples of 5 print <code>Buzz</code>, and for both print <code>FizzBuzz</code>.',
      starter: 'for n in range(1, 16):\n    if n % 15 == 0:\n        print("FizzBuzz")\n    else:\n        print(n)\n',
      expect: '1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz',
      requires: ['for', 'if', 'elif'],
      hint: 'Add elif n % 3 == 0 and elif n % 5 == 0 between the if and the else.',
      solution: 'for n in range(1, 16):\n    if n % 15 == 0:\n        print("FizzBuzz")\n    elif n % 3 == 0:\n        print("Fizz")\n    elif n % 5 == 0:\n        print("Buzz")\n    else:\n        print(n)\n' },

    // Functions
    { id: 'f1', group: 'def', title: 'Hiss Function',
      task: 'Make a function <code>hiss()</code> that prints <code>Hisssss!</code>. Call it 2 times.',
      starter: 'def hiss():\n    print("Hi")\n',
      expect: 'Hisssss!\nHisssss!',
      requires: ['def'],
      hint: 'Fix the print, then write hiss() twice at the bottom (no spaces in front).',
      solution: 'def hiss():\n    print("Hisssss!")\n\nhiss()\nhiss()\n' },
    { id: 'f2', group: 'def', title: 'Greeter',
      task: 'Make <code>greet(name)</code> that prints <code>Hello, NAME!</code>. Call it with <code>"Ana"</code> and with <code>"Leo"</code>.',
      starter: 'def greet(name):\n    print("Hello")\n',
      expect: 'Hello, Ana!\nHello, Leo!',
      requires: ['def', 'parameter'],
      hint: 'print("Hello, " + name + "!")',
      solution: 'def greet(name):\n    print("Hello, " + name + "!")\n\ngreet("Ana")\ngreet("Leo")\n' },
    { id: 'f3', group: 'def', title: 'Double It',
      task: 'Make a function <code>double(n)</code> that <b>returns</b> n times 2. (No need to print, the checker will test it!)',
      starter: 'def double(n):\n    return n\n',
      tests: 'assert double(2) == 4, "double(2) should give 4"\nassert double(10) == 20, "double(10) should give 20"\nassert double(0) == 0, "double(0) should give 0"',
      requires: ['def', 'return'],
      hint: 'return n * 2',
      solution: 'def double(n):\n    return n * 2\n' },
    { id: 'f4', group: 'def', title: 'Biggest',
      task: 'Make <code>biggest(a, b)</code> that returns the bigger of two numbers. Use if, don\u2019t use max()!',
      starter: 'def biggest(a, b):\n    return a\n',
      tests: 'assert biggest(3, 9) == 9, "biggest(3, 9) should be 9"\nassert biggest(10, 2) == 10, "biggest(10, 2) should be 10"\nassert biggest(5, 5) == 5, "biggest(5, 5) should be 5"',
      requires: ['def', 'if', 'return'],
      hint: 'if a > b:\n    return a\nelse:\n    return b',
      solution: 'def biggest(a, b):\n    if a > b:\n        return a\n    else:\n        return b\n' },

    // Lists
    { id: 's1', group: 'lists', title: 'Fruit Basket',
      task: 'Make a list <code>fruits</code> with <code>"apple"</code>, <code>"banana"</code> and <code>"cherry"</code>. Print each fruit with a loop.',
      starter: 'fruits = ["apple"]\n',
      expect: 'apple\nbanana\ncherry',
      requires: ['list', 'for'],
      hint: 'for fruit in fruits:\n    print(fruit)',
      solution: 'fruits = ["apple", "banana", "cherry"]\nfor fruit in fruits:\n    print(fruit)\n' },
    { id: 's2', group: 'lists', title: 'First and Last',
      task: 'Print the <b>first</b> and the <b>last</b> item of <code>blocks</code>. Remember, counting starts at 0!',
      starter: 'blocks = ["grass", "dirt", "stone", "gold"]\n',
      expect: 'grass\ngold',
      hint: 'blocks[0] is the first. blocks[-1] is the last!',
      solution: 'blocks = ["grass", "dirt", "stone", "gold"]\nprint(blocks[0])\nprint(blocks[-1])\n' },
    { id: 's3', group: 'lists', title: 'Collect Gems',
      task: 'Start with an empty list <code>bag = []</code>. Use <code>bag.append()</code> to add <code>"ruby"</code> and <code>"emerald"</code>. Then print <code>len(bag)</code>.',
      starter: 'bag = []\n',
      expect: '2',
      tests: 'assert bag == ["ruby", "emerald"], "bag should be [\\"ruby\\", \\"emerald\\"]"',
      requires: ['list'],
      hint: 'bag.append("ruby")',
      solution: 'bag = []\nbag.append("ruby")\nbag.append("emerald")\nprint(len(bag))\n' },
    { id: 's4', group: 'lists', title: 'Total Score',
      task: 'Add up all the numbers in <code>scores</code> with a loop and print the total.',
      starter: 'scores = [10, 25, 5, 40]\ntotal = 0\n',
      expect: '80',
      requires: ['for'],
      hint: 'for s in scores:\n    total = total + s',
      solution: 'scores = [10, 25, 5, 40]\ntotal = 0\nfor s in scores:\n    total = total + s\nprint(total)\n' },

    // Challenges
    { id: 'b1', group: 'boss', title: 'Stars Tower',
      task: 'Print a tower of stars:<pre>*\n**\n***\n****</pre>Tip: <code>"*" * 3</code> makes <code>***</code>',
      starter: 'for i in range(1, 5):\n    print(i)\n',
      expect: '*\n**\n***\n****',
      requires: ['for'],
      hint: 'print("*" * i)',
      solution: 'for i in range(1, 5):\n    print("*" * i)\n' },
    { id: 'b2', group: 'boss', title: 'Count the Apples',
      task: 'Make a function <code>count_apples(items)</code> that returns how many times <code>"apple"</code> is in the list.',
      starter: 'def count_apples(items):\n    count = 0\n    return count\n',
      tests: 'assert count_apples(["apple", "rock", "apple"]) == 2, "count_apples([\\"apple\\", \\"rock\\", \\"apple\\"]) should be 2"\nassert count_apples([]) == 0, "An empty list has 0 apples"\nassert count_apples(["tree"]) == 0, "[\\"tree\\"] has 0 apples"',
      requires: ['def', 'for', 'if'],
      hint: 'for item in items:\n    if item == "apple":\n        count = count + 1',
      solution: 'def count_apples(items):\n    count = 0\n    for item in items:\n        if item == "apple":\n            count = count + 1\n    return count\n' },
    { id: 'b3', group: 'boss', title: 'Reverse Word',
      task: 'Make <code>reverse(word)</code> that returns the word backwards, so <code>reverse("snake")</code> gives <code>"ekans"</code>. Use a loop!',
      starter: 'def reverse(word):\n    result = ""\n    return result\n',
      tests: 'assert reverse("snake") == "ekans", "reverse(\\"snake\\") should be \\"ekans\\""\nassert reverse("a") == "a"\nassert reverse("") == ""',
      requires: ['def', 'for'],
      hint: 'for letter in word:\n    result = letter + result',
      solution: 'def reverse(word):\n    result = ""\n    for letter in word:\n        result = letter + result\n    return result\n' },
    { id: 'b4', group: 'boss', title: 'Biggest in List',
      task: 'Make <code>largest(numbers)</code> that returns the biggest number in the list, without using max().',
      starter: 'def largest(numbers):\n    best = numbers[0]\n    return best\n',
      tests: 'assert largest([3, 8, 2]) == 8, "largest([3, 8, 2]) should be 8"\nassert largest([7]) == 7\nassert largest([-5, -2, -9]) == -2, "largest([-5, -2, -9]) should be -2"',
      requires: ['def', 'for', 'if'],
      hint: 'for n in numbers:\n    if n > best:\n        best = n',
      solution: 'def largest(numbers):\n    best = numbers[0]\n    for n in numbers:\n        if n > best:\n            best = n\n    return best\n' }
  ];

  root.PracticeData = { GROUPS: GROUPS, EXERCISES: EXERCISES };
})(typeof self !== 'undefined' ? self : this);
